# Generated by Django 5.2 on 2025-04-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userJoinDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
