# Generated by Django 5.2 on 2025-04-16 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminId', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('adminEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.user')),
                ('professorClass', models.TextField()),
            ],
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.user')),
                ('studentClasses', models.TextField()),
            ],
            bases=('api.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='userAge',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
