# Generated by Django 5.2 on 2025-04-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_admin_professor_student_user_userage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
