# Generated by Django 5.2 on 2025-04-23 13:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_admin_remove_student_user_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('userId', models.UUIDField(default=uuid.UUID('6ccec80c-faa5-4661-a733-2edf376ed719'), editable=False, primary_key=True, serialize=False)),
                ('userName', models.CharField(default='John Doe', max_length=100)),
                ('userJoinDate', models.DateField(auto_now_add=True)),
                ('lastJoined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('userId', models.UUIDField(default=uuid.UUID('6ccec80c-faa5-4661-a733-2edf376ed719'), editable=False, primary_key=True, serialize=False)),
                ('userName', models.CharField(default='John Doe', max_length=100)),
                ('userJoinDate', models.DateField(auto_now_add=True)),
                ('studentAge', models.PositiveIntegerField(default=0)),
                ('classesMissedCount', models.IntegerField(default=0)),
                ('classesMissed', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('userId', models.UUIDField(default=uuid.UUID('6ccec80c-faa5-4661-a733-2edf376ed719'), editable=False, primary_key=True, serialize=False)),
                ('userName', models.CharField(default='John Doe', max_length=100)),
                ('userJoinDate', models.DateField(auto_now_add=True)),
                ('teacherSubject', models.CharField(max_length=100)),
                ('teacherSchedule', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
