# Generated by Django 5.2 on 2025-04-23 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_admin_student_teacher_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='userEmail',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='userEmail',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='userEmail',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='userId',
            field=models.UUIDField(default=uuid.UUID('c7e872f8-da32-463d-81bd-56fdd462f391'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='userId',
            field=models.UUIDField(default=uuid.UUID('c7e872f8-da32-463d-81bd-56fdd462f391'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='userId',
            field=models.UUIDField(default=uuid.UUID('c7e872f8-da32-463d-81bd-56fdd462f391'), editable=False, primary_key=True, serialize=False),
        ),
    ]
