# Generated by Django 5.2 on 2025-04-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_admin_userid_alter_student_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
