# Generated by Django 5.2 on 2025-04-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_admin_userid_alter_student_userid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(default='John Doe', max_length=100)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userJoinDate', models.DateField(auto_now_add=True)),
                ('sponsorDescription', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
