# Generated by Django 5.2 on 2025-05-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=100)),
                ('courseImage', models.ImageField(blank=True, default='fallback.jpeg', upload_to='')),
                ('couseDescription', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='classesMissed',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherSchedule',
            field=models.TextField(null=True),
        ),
    ]
