# Generated by Django 5.2 on 2025-05-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_course_alter_student_classesmissed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseTests',
            field=models.TextField(blank=True),
        ),
    ]
