# Generated by Django 5.2 on 2025-06-04 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.profile')),
                ('studentAge', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('classesMissedCount', models.IntegerField(blank=True, default=0, null=True)),
                ('classesMissed', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherData',
            fields=[
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.profile')),
                ('teacherSubject', models.CharField(blank=True, max_length=100, null=True)),
                ('teacherSchedule', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='couseDescription',
            new_name='courseDescription',
        ),
        migrations.AlterField(
            model_name='course',
            name='courseImage',
            field=models.ImageField(blank=True, default='fallback.jpeg', upload_to='course_images/'),
        ),
        migrations.CreateModel(
            name='DesempenhoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_qualitativa', models.CharField(blank=True, choices=[('', 'Não Avaliado'), ('muito_bom', 'Muito Bom'), ('bom', 'Bom'), ('satisfatorio', 'Satisfatório'), ('regular', 'Regular'), ('insatisfatorio', 'Insatisfatório')], default='', max_length=20)),
                ('faltas', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materia')),
            ],
            options={
                'unique_together': {('aluno', 'materia')},
            },
        ),
    ]
