# Generated by Django 5.2 on 2025-06-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_materia_studentdata_teacherdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dados_calendario_json',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
