# Generated by Django 5.2 on 2025-06-05 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_student_courseseval_student_coursesregistred'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='coursesRegistred',
            new_name='coursesReg',
        ),
    ]
