# Generated by Django 5.2 on 2025-06-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_coursesregistred_student_coursesreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
            ],
        ),
    ]
