# Generated by Django 5.2 on 2025-06-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_duvida'),
    ]

    operations = [
        migrations.AddField(
            model_name='duvida',
            name='destinatario',
            field=models.CharField(choices=[('Geral', 'Geral'), ('Professor', 'Professor'), ('Administrador', 'Administrador'), ('Professores', 'Professores')], default='Geral', max_length=20),
        ),
        migrations.AddField(
            model_name='duvida',
            name='titulo',
            field=models.CharField(default=10, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='duvida',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
