# Generated by Django 5.2 on 2025-06-05 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_duvida_destinatario_duvida_titulo_alter_duvida_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duvida',
            options={'verbose_name': 'Dúvida', 'verbose_name_plural': 'Dúvidas'},
        ),
        migrations.AddField(
            model_name='duvida',
            name='remetente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duvidas_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='duvida',
            name='destinatario',
            field=models.CharField(max_length=50),
        ),
    ]
